### ISSUE TITLE
Aggiungi Campi Anagrafica Clienti

### ISSUE THREAD

**Issue by adpabbonati** [rssntn67/SubscriptionManagementDashboard#2]
Nel form mancano i seguenti campi

titolo da selezionare in un menu a tendina
partita iva
codice fiscale

**Comment by adpabbonati** [comment]
Inoltre sarebbe opportuno al titolo aggiungere il campo sotto intestazione ad es: c/o Parrocchia del SS Sacramento

**Comment by rssntn67** [comment]
Caterina....la lista delle categorie.....andiamo.....
