### ISSUE TITLE
Aggiungi Categorie alla Anagrafica Clienti

### ISSUE THREAD

**Issue by adpabbonati** [rssntn67/SubscriptionManagementDashboard#3]
Qui Caterina aggiunge le sue categorie

**Comment by adpabbonati** [comment]
Buongiorno abbiamo individuato un elenco di categorie da inserire:

28 | ABBONATI CON SCONTO TESTATE-- | --
20 | BM CASSA
66 | CARDINALI
141 | CARICHE SOCIALI E RAPPRESENTANTI
200 | CCP BM CASSA
020 | CENTRO DIOCESANO BERGAMO
00011 | CENTRO DIOCESANO ROMA
10 | CONSIGLIO NAZIONALE A.D.P.
49 | CONSIGLIO PRESIDENZA ADP
201 | CONTRASSEGNO BM CASSA
7 | CURIE DIOCESANE
117 | DDABRUZZO/MOLISE
32 | DDBASILICATA
92 | DDCALABRIA
48 | DDCAMPANIA
94 | DDEMILIA
91 | DDLAZIO
113 | DDLIGURIA
112 | DDLOMBARDIA
116 | DDMARCHE
118 | DDMOLISE
111 | DDPIEMONTE
29 | DDPUGLIA
114 | DDSARDEGNA
95 | DDSICILIA
33 | DDTOSCANA
115 | DDTRIVENETO
38 | DDUMBRIA
140 | DELEGATI REGIONALI
1 | DIRETTORE DIOCESANO
00013 | DIRETTORI ZONE MILANO
144 | MARISA BISI ELENCO
15 | MEMBRI DIREZIONE ADP
9 | OMAGGIO GESUITI
012 | PDABRUZZO e MOLISE
017 | PDBASILICATA
018 | PDCALABRIA
019 | PDCAMPANIA
013 | PDEMILIA ROMAGNA
011 | PDLAZIO
014 | PDLIGURIA
0190 | PDLOMBARDIA
016 | PDMARCHE
015 | PDPIEMONTE/VALLE D.
0191 | PDPUGLIA
01 | PDSARDEGNA
0192 | PDSICILIA
0193 | PDTOSCANA
0194 | PDTRIVENETO
010 | PDUMBRIA
52 | Presidenti e Referenti DIOCESANI
12 | PROMOTORI REGIONALI
143 | RIVISTE OMAGGIO CURIA GENERALIZIA
202 | SOLO ELENCO BM CASSA
80 | VABRUZZO
35 | VBASILICATA
61 | VCALABRIA
58 | VCAMPANIA
100 | VEMILIA
8 | VESCOVI
120 | VESCOVO AUSILIARE
110 | VLAZIO
101 | VLIGURIA
102 | VLOMBARDIA
60 | VMARCHE
45 | VMETROPOLIA LECCE
81 | VMOLISE
103 | VPIEMONTE
31 | VPUGLIA
104 | VSARDEGNA
59 | VSICILIA
36 | VTOSCANA
105 | VTRIVENETO
37 | VUMBRIA

**Comment by rssntn67** [comment]
si chiaro

**Comment by rssntn67** [comment]
Ma per esempio VUMBRIA e VTRIVENETO sono mutuamente esclusivi....

**Comment by rssntn67** [comment]
Possiamo raggrupparli...e non mi sembrano troppe
