### ISSUE TITLE
Aggiungi Campo Abbonamenti

### ISSUE THREAD

**Issue by adpabbonati** [rssntn67/SubscriptionManagementDashboard#5]
Per prima cosa bisogna aggiungere un campo opzionale nel caso in cui a pagare sia un altro Cliente.
In questo caso la rivista va spedita al destinatario e il conto al intestatario

Aggiungere la lista delle riviste su cui fare l'abbonamento

Aggiungere il campo dell'Abbonamento relativo alla tipologia (UNA TANTUM,  SEMESTRALE,ANNUALE) 

Aggiungere il CAMPO inizio Validità

**Comment by adpabbonati** [comment]
Di Base Gli abbonamenti iunizianoa gennaio e termino sempre a Dicembre

**Comment by rssntn67** [comment]
Inoltre bisogna aggiungere la fondamentale proprieta' se l'abbonamento e' stato incassato
